# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/code" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: '*crypto*' # Leave my cryptography vulns alone ?!
  - package-ecosystem: "pip" # IGNORE anything in /code/users (pip)
    directory: "/code/users"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: '*'
  - package-ecosystem: "npm" # IGNORE anything in /code/users (pip)
    directory: "/code/users" 
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: '*'
